name: Example to run sitespeed.io on Windows
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: windows-2025
    if: ${{ !contains(github.event.head_commit.message, 'docs:') }}
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
    - name: Install sitespeed.io
      run: npm install sitespeed.io -g
      shell: bash
    - name: Install dependencies
      run: |
        choco install ffmpeg 
        choco outdated
        choco install python
        choco install googlechrome
        python -m pip install --upgrade --user pip
        python -m pip install --upgrade --user setuptools
        python -m pip install --user pyssim OpenCV-Python Numpy scipy
        python -m pip --version
        python -m pip show Pillow
        python -m pip show pyssim
      shell: cmd
    - name: Example running test on Windows
      run: sitespeed.io -n 1 --video --visualMetrics --viewPort 1024x768 https://www.sitespeed.io/ 
      shell: bash